### ISSUE TITLE
Reproducible HotSpot crash with JDK 10

### ISSUE THREAD

**Issue by stefan-reich** [openimaj/openimaj#155] opened 2018-10-21 17:46 UTC
Hi, whenever I use the HaarCascade face detector, my JDK 10 crashes. Same program runs fine in JDK 8. Platform = Linux/64.

It is an older version of OpenIMAJ though, so that might be the reason. I'm trying to compile from GitHub right now.

**Comment by jonhare** [comment] 2018-10-21 18:05
That's weird - same issue seems to be occurring here on Windows (scroll down to the last comments): https://github.com/openimaj/openimaj/issues/154

I'm not really sure what to suggest though - I'm not aware that any native code is being used so it seems more likely that its a JDK bug. Have you got a stack-trace that indicates where it might be breaking?

**Comment by stefan-reich** [comment] 2018-10-21 22:44
I do have the [HotSpot error logs](http://butter.botcompany.de:8080/1015408/raw/1400141/openimaj-error.zip) if that helps?

**Comment by jonhare** [comment] 2018-10-22 18:18
So, the hotspot error log suggests it is actually the hotspot compiler that is crashing... I've just posted build instructions on your other issue - let me know if you're able to make a build & if the new jar fixes the issue.

**Comment by jonhare** [comment] 2018-10-22 20:48
I've now just setup JDK 11 on a linux box and can confirm this problem. It doesn't go away with a clean install of OpenIMAJ either (when built with that JDK). The problem literally seems to be a bug in the C2 optimiser in the JRE. You can work-around it by disabling C2 using the `-XX:TieredStopAtLevel=1` flag.

**Comment by jonhare** [comment] 2018-10-22 21:54
I've reported a bug with Oracle - internal ref 9057763

**Comment by jonhare** [comment] 2018-10-24 08:04
Ok, response from Oracle: https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8212893

It is a bug from a regression after JDK 9 & has been fixed in JDK 11 apparently

**Closed by jonhare** 2018-10-24 08:04 UTC
